const PriceData = [
  {
    title: "USA Window Film",
    category: "Window Film",
    suv: "4x4",
    priceSuv: "$700",
    sedan: "SEDAN",
    priceSedan: "$600",
  },
  {
    title: "Nano Ceramic window film",
    category: "Window Film",
    suv: "4x4",
    priceSuv: "$1900",
    sedan: "SEDAN",
    priceSedan: "$1700",
  },
  {
    title: "Xpel XR+ window film",
    category: "Window Film",
    suv: "4x4",
    priceSuv: "$3800",
    sedan: "SEDAN",
    priceSedan: "$3300",
  },
  {
    title: "Nano Ceramic Coating",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$1200",
    sedan: "SEDAN",
    priceSedan: "$1000",
  },
  {
    title: "Nano Ceramic for Rimps",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$400",
    sedan: "SEDAN",
    priceSedan: "$400",
  },
  {
    title: "Nano Ceramic for Leather",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$400",
    sedan: "SEDAN",
    priceSedan: "$250",
  },
  {
    title: "Nano Ceramic for Coating",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$2000",
    sedan: "SEDAN",
    priceSedan: "$1700",
  },
  {
    title: "Full car American PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$10,000",
    sedan: "SEDAN",
    priceSedan: "$9,000",
  },
  {
    title: "Car front American PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$3900",
    sedan: "SEDAN",
    priceSedan: "$3500",
  },
  {
    title: "Car face American PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$2900",
    sedan: "SEDAN",
    priceSedan: "$2600",
  },
  {
    title: "Full Car American PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$12,000",
    sedan: "SEDAN",
    priceSedan: "$11,000",
  },
  {
    title: "Car front American PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$5500",
    sedan: "SEDAN",
    priceSedan: "$4700",
  },
  {
    title: "Car face American PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$3500",
    sedan: "SEDAN",
    priceSedan: "$3000",
  },
  {
    title: "Full Car German PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$15000",
    sedan: "SEDAN",
    priceSedan: "$13000",
  },
  {
    title: "Car front German PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$7000",
    sedan: "SEDAN",
    priceSedan: "$6000",
  },
  {
    title: "Full Car German PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$15000",
    sedan: "SEDAN",
    priceSedan: "$13000",
  },
  {
    title: "Car front German PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$7000",
    sedan: "SEDAN",
    priceSedan: "$6000",
  },
  {
    title: "Car face German PPF",
    category: "Protection",
    suv: "4x4",
    priceSuv: "$4200",
    sedan: "SEDAN",
    priceSedan: "$3500",
  },
  {
    title: "Interior Polish",
    category: "Polish",
    suv: "4x4",
    priceSuv: "$500",
    sedan: "SEDAN",
    priceSedan: "$400",
  },
  {
    title: "Exterior Polish",
    category: "Polish",
    suv: "4x4",
    priceSuv: "$800",
    sedan: "SEDAN",
    priceSedan: "$650",
  },
  {
    title: "Interior Polish (Diamond)",
    category: "Polish",
    suv: "4x4",
    priceSuv: "$600",
    sedan: "SEDAN",
    priceSedan: "$500",
  },
  {
    title: "Exterior Polish (Diammond)",
    category: "Polish",
    suv: "4x4",
    priceSuv: "$950",
    sedan: "SEDAN",
    priceSedan: "$800",
  },
  {
    title: "Full Detailing",
    category: "Polish",
    suv: "4x4",
    priceSuv: "$650",
    sedan: "SEDAN",
    priceSedan: "$550",
  },
  {
    title: "Head lights Polish",
    category: "Others",
    suv: "4x4",
    priceSuv: "$150",
    sedan: "SEDAN",
    priceSedan: "$150",
  },
  {
    title: "Travel Protection",
    category: "Others",
    suv: "4x4",
    priceSuv: "$250",
    sedan: "SEDAN",
    priceSedan: "$250",
  },
  {
    title: "Head lights inside clean",
    category: "Others",
    suv: "4x4",
    priceSuv: "As per car type",
    sedan: "SEDAN",
    priceSedan: "",
  },
  {
    title: "Head lights cover change",
    category: "Others",
    suv: "4x4",
    priceSuv: "As per car type",
    sedan: "SEDAN",
    priceSedan: "",
  },
  {
    title: "Remove and install sticker",
    category: "Others",
    suv: "4x4",
    priceSuv: "As per car type",
    sedan: "SEDAN",
    priceSedan: "",
  },
  {
    title: "SUV Car/Big",
    category: "Car Washing",
    suv: "Full Wash",
    priceSuv: "$35",
    sedan: "Baby Wash",
    priceSedan: "$25",
  },
  {
    title: "SUV Car",
    category: "Car Washing",
    suv: "Full Wash",
    priceSuv: "$30",
    sedan: "Baby Wash",
    priceSedan: "$20",
  },
  {
    title: "Saloon Car",
    category: "Car Washing",
    suv: "Full Wash",
    priceSuv: "$25",
    sedan: "Baby Wash",
    priceSedan: "$15",
  },
  {
    title: "Small Bus",
    category: "Car Washing",
    suv: "Full Wash",
    priceSuv: "$40",
    sedan: "Baby Wash",
    priceSedan: "$30",
  },
  {
    title: "Medium Bus",
    category: "Car Washing",
    suv: "Full Wash",
    priceSuv: "$50",
    sedan: "Baby Wash",
    priceSedan: "$40",
  },
  {
    title: "Motorcycle",
    category: "Car Washing",
    suv: "Full Wash",
    priceSuv: "$15",
    sedan: "Baby Wash",
    priceSedan: "--",
  },
];

export default PriceData;
