const PriceData = [
  {
    title: { en: "USA Window Film", ar: "فيلم نوافذ أمريكي" },
    category: { en: "Window Film", ar: "فيلم نوافذ" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 700", ar: "700 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 600", ar: "600 الريال" },
  },
  {
    title: { en: "Nano Ceramic window film", ar: "فيلم نوافذ سيراميك نانو" },
    category: { en: "Window Film", ar: "فيلم نوافذ" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 1900", ar: "1900 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 1700", ar: "1700 الريال" },
  },
  {
    title: { en: "Xpel XR+ window film", ar: "فيلم نوافذ Xpel XR+" },
    category: { en: "Window Film", ar: "فيلم نوافذ" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 3800", ar: "3800 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 3300", ar: "3300 الريال" },
  },
  {
    title: { en: "Nano Ceramic Coating", ar: "طلاء سيراميك نانو" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 1200", ar: "1200 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 1000", ar: "1000 الريال" },
  },
  {
    title: { en: "Nano Ceramic for Rimps", ar: "سيراميك نانو للعجلات" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 400", ar: "400 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 400", ar: "400 الريال" },
  },
  {
    title: { en: "Nano Ceramic for Leather", ar: "سيراميك نانو للجلد" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 400", ar: "400 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 250", ar: "250 الريال" },
  },
  {
    title: { en: "Nano Ceramic for Coating", ar: "سيراميك نانو للتغطية" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 2000", ar: "2000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 1700", ar: "1700 الريال" },
  },
  {
    title: { en: "Full car American PPF", ar: "PPF كامل للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 10,000", ar: "10000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 9,000", ar: "9000 الريال" },
  },
  {
    title: { en: "Car front American PPF", ar: "PPF أمامي للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 3900", ar: "3900 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 3500", ar: "3500 الريال" },
  },
  {
    title: { en: "Car face American PPF", ar: "PPF وجه السيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 2900", ar: "2900 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 2600", ar: "2600 الريال" },
  },
  {
    title: { en: "Full Car American PPF", ar: "PPF كامل للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 12,000", ar: "12000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 11,000", ar: "11000 الريال" },
  },
  {
    title: { en: "Car front American PPF", ar: "PPF أمامي للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 5500", ar: "5500 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 4700", ar: "4700 الريال" },
  },
  {
    title: { en: "Car face American PPF", ar: "PPF وجه السيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 3500", ar: "3500 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 3000", ar: "3000 الريال" },
  },
  {
    title: { en: "Full Car German PPF", ar: "PPF كامل للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 15000", ar: "15000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 13000", ar: "13000 الريال" },
  },
  {
    title: { en: "Car front German PPF", ar: "PPF أمامي للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 7000", ar: "7000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 6000", ar: "6000 الريال" },
  },
  {
    title: { en: "Full Car German PPF", ar: "PPF كامل للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 15000", ar: "15000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 13000", ar: "13000 الريال" },
  },
  {
    title: { en: "Car front German PPF", ar: "PPF أمامي للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 7200", ar: "7200 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 6200", ar: "6200 الريال" },
  },
  {
    title: { en: "Car front German PPF", ar: "حماية مقدمة السيارة الألمانية" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 7000", ar: "7000 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 6000", ar: "6000 الريال" },
  },
  {
    title: { en: "Car face German PPF", ar: "حماية وجه السيارة الألمانية" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 4200", ar: "4200 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 3500", ar: "3500 الريال" },
  },
  {
    title: { en: "Interior Polish", ar: "تلميع داخلي" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 500", ar: "500 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 400", ar: "400 الريال" },
  },
  {
    title: { en: "Exterior Polish", ar: "تلميع خارجي" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 800", ar: "800 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 650", ar: "650 الريال" },
  },
  {
    title: { en: "Interior Polish (Diamond)", ar: "تلميع داخلي (ألماسي)" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 600", ar: "600 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 500", ar: "500 الريال" },
  },
  {
    title: { en: "Exterior Polish (Diammond)", ar: "تلميع خارجي (ألماسي)" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 950", ar: "950 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 800", ar: "800 الريال" },
  },
  {
    title: { en: "Full Detailing", ar: "تفاصيل كاملة" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 650", ar: "650 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 550", ar: "550 الريال" },
  },
  {
    title: { en: "Head lights Polish", ar: "تلميع المصابيح الأمامية" },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 150", ar: "150 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 150", ar: "150 الريال" },
  },
  {
    title: { en: "Travel Protection", ar: "حماية السفر" },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "QR 250", ar: "250 الريال" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "QR 250", ar: "250 الريال" },
  },
  {
    title: {
      en: "Head lights inside clean",
      ar: "تنظيف داخلي للمصابيح الأمامية",
    },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "As per car type", ar: "حسب نوع السيارة" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "", ar: "" },
  },
  {
    title: {
      en: "Head lights cover change",
      ar: "تغيير غطاء المصابيح الأمامية",
    },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "As per car type", ar: "حسب نوع السيارة" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "", ar: "" },
  },
  {
    title: { en: "Remove and install sticker", ar: "إزالة وتركيب الاستيكر" },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "As per car type", ar: "حسب نوع السيارة" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "", ar: "" },
  },
  {
    title: { en: "SUV Car/Big", ar: "سيارة الدفع الرباعي/كبير" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "QR 35", ar: "35 الريال" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "QR 25", ar: "25 الريال" },
  },
  {
    title: { en: "SUV Car", ar: "سيارة الدفع الرباعي" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "QR 30", ar: "30 الريال" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "QR 20", ar: "20 الريال" },
  },
  {
    title: { en: "Saloon Car", ar: "سيارة الصالون" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "QR 25", ar: "25 الريال" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "QR 15", ar: "15 الريال" },
  },
  {
    title: { en: "Small Bus", ar: "حافلة صغيرة" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "QR 40", ar: "40 الريال" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "QR 30", ar: "30 الريال" },
  },
  {
    title: { en: "Medium Bus", ar: "حافلة متوسطة" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "QR 50", ar: "50 الريال" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "QR 40", ar: "40 الريال" },
  },
  {
    title: { en: "Motorcycle", ar: "دراجة نارية" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "QR 20", ar: "20 الريال" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "QR 10", ar: "10 الريال" },
  },
  {
    title: { en: "Complete Car Detail", ar: "تفاصيل كاملة للسيارة" },
    category: { en: "Detailing", ar: "تفاصيل" },
    suv: { en: "Full Detail", ar: "تفاصيل كاملة" },
    priceSuv: { en: "QR 700", ar: "700 الريال" },
    sedan: { en: "Full Detail", ar: "تفاصيل كاملة" },
    priceSedan: { en: "QR 500", ar: "500 الريال" },
  },
];
export default PriceData;
