const PriceData = [
  {
    title: { en: "USA Window Film", ar: "فيلم نوافذ أمريكي" },
    category: { en: "Window Film", ar: "فيلم نوافذ" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$700", ar: "700 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$600", ar: "600 دولار" },
  },
  {
    title: { en: "Nano Ceramic window film", ar: "فيلم نوافذ سيراميك نانو" },
    category: { en: "Window Film", ar: "فيلم نوافذ" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$1900", ar: "1900 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$1700", ar: "1700 دولار" },
  },
  {
    title: { en: "Xpel XR+ window film", ar: "فيلم نوافذ Xpel XR+" },
    category: { en: "Window Film", ar: "فيلم نوافذ" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$3800", ar: "3800 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$3300", ar: "3300 دولار" },
  },
  {
    title: { en: "Nano Ceramic Coating", ar: "طلاء سيراميك نانو" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$1200", ar: "1200 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$1000", ar: "1000 دولار" },
  },
  {
    title: { en: "Nano Ceramic for Rimps", ar: "سيراميك نانو للعجلات" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$400", ar: "400 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$400", ar: "400 دولار" },
  },
  {
    title: { en: "Nano Ceramic for Leather", ar: "سيراميك نانو للجلد" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$400", ar: "400 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$250", ar: "250 دولار" },
  },
  {
    title: { en: "Nano Ceramic for Coating", ar: "سيراميك نانو للتغطية" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$2000", ar: "2000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$1700", ar: "1700 دولار" },
  },
  {
    title: { en: "Full car American PPF", ar: "PPF كامل للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$10,000", ar: "10000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$9,000", ar: "9000 دولار" },
  },
  {
    title: { en: "Car front American PPF", ar: "PPF أمامي للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$3900", ar: "3900 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$3500", ar: "3500 دولار" },
  },
  {
    title: { en: "Car face American PPF", ar: "PPF وجه السيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$2900", ar: "2900 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$2600", ar: "2600 دولار" },
  },
  {
    title: { en: "Full Car American PPF", ar: "PPF كامل للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$12,000", ar: "12000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$11,000", ar: "11000 دولار" },
  },
  {
    title: { en: "Car front American PPF", ar: "PPF أمامي للسيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$5500", ar: "5500 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$4700", ar: "4700 دولار" },
  },
  {
    title: { en: "Car face American PPF", ar: "PPF وجه السيارة أمريكي" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$3500", ar: "3500 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$3000", ar: "3000 دولار" },
  },
  {
    title: { en: "Full Car German PPF", ar: "PPF كامل للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$15000", ar: "15000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$13000", ar: "13000 دولار" },
  },
  {
    title: { en: "Car front German PPF", ar: "PPF أمامي للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$7000", ar: "7000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$6000", ar: "6000 دولار" },
  },
  {
    title: { en: "Full Car German PPF", ar: "PPF كامل للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$15000", ar: "15000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$13000", ar: "13000 دولار" },
  },
  {
    title: { en: "Car front German PPF", ar: "PPF أمامي للسيارة ألماني" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$7200", ar: "7200 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$6200", ar: "6200 دولار" },
  },
  {
    title: { en: "Car front German PPF", ar: "حماية مقدمة السيارة الألمانية" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$7000", ar: "7000 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$6000", ar: "6000 دولار" },
  },
  {
    title: { en: "Car face German PPF", ar: "حماية وجه السيارة الألمانية" },
    category: { en: "Protection", ar: "حماية" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$4200", ar: "4200 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$3500", ar: "3500 دولار" },
  },
  {
    title: { en: "Interior Polish", ar: "تلميع داخلي" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$500", ar: "500 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$400", ar: "400 دولار" },
  },
  {
    title: { en: "Exterior Polish", ar: "تلميع خارجي" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$800", ar: "800 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$650", ar: "650 دولار" },
  },
  {
    title: { en: "Interior Polish (Diamond)", ar: "تلميع داخلي (ألماسي)" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$600", ar: "600 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$500", ar: "500 دولار" },
  },
  {
    title: { en: "Exterior Polish (Diammond)", ar: "تلميع خارجي (ألماسي)" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$950", ar: "950 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$800", ar: "800 دولار" },
  },
  {
    title: { en: "Full Detailing", ar: "تفاصيل كاملة" },
    category: { en: "Polish", ar: "تلميع" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$650", ar: "650 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$550", ar: "550 دولار" },
  },
  {
    title: { en: "Head lights Polish", ar: "تلميع المصابيح الأمامية" },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$150", ar: "150 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$150", ar: "150 دولار" },
  },
  {
    title: { en: "Travel Protection", ar: "حماية السفر" },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "$250", ar: "250 دولار" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "$250", ar: "250 دولار" },
  },
  {
    title: {
      en: "Head lights inside clean",
      ar: "تنظيف داخلي للمصابيح الأمامية",
    },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "As per car type", ar: "حسب نوع السيارة" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "", ar: "" },
  },
  {
    title: {
      en: "Head lights cover change",
      ar: "تغيير غطاء المصابيح الأمامية",
    },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "As per car type", ar: "حسب نوع السيارة" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "", ar: "" },
  },
  {
    title: { en: "Remove and install sticker", ar: "إزالة وتركيب الاستيكر" },
    category: { en: "Others", ar: "أخرى" },
    suv: { en: "4x4", ar: "4x4" },
    priceSuv: { en: "As per car type", ar: "حسب نوع السيارة" },
    sedan: { en: "SEDAN", ar: "سيدان" },
    priceSedan: { en: "", ar: "" },
  },
  {
    title: { en: "SUV Car/Big", ar: "سيارة الدفع الرباعي/كبير" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "$35", ar: "35 دولار" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "$25", ar: "25 دولار" },
  },
  {
    title: { en: "SUV Car", ar: "سيارة الدفع الرباعي" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "$30", ar: "30 دولار" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "$20", ar: "20 دولار" },
  },
  {
    title: { en: "Saloon Car", ar: "سيارة الصالون" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "$25", ar: "25 دولار" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "$15", ar: "15 دولار" },
  },
  {
    title: { en: "Small Bus", ar: "حافلة صغيرة" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "$40", ar: "40 دولار" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "$30", ar: "30 دولار" },
  },
  {
    title: { en: "Medium Bus", ar: "حافلة متوسطة" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "$50", ar: "50 دولار" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "$40", ar: "40 دولار" },
  },
  {
    title: { en: "Motorcycle", ar: "دراجة نارية" },
    category: { en: "Car Washing", ar: "غسيل السيارات" },
    suv: { en: "Full Wash", ar: "غسل كامل" },
    priceSuv: { en: "$20", ar: "20 دولار" },
    sedan: { en: "Baby Wash", ar: "غسل صغير" },
    priceSedan: { en: "$10", ar: "10 دولار" },
  },
  {
    title: { en: "Complete Car Detail", ar: "تفاصيل كاملة للسيارة" },
    category: { en: "Detailing", ar: "تفاصيل" },
    suv: { en: "Full Detail", ar: "تفاصيل كاملة" },
    priceSuv: { en: "$700", ar: "700 دولار" },
    sedan: { en: "Full Detail", ar: "تفاصيل كاملة" },
    priceSedan: { en: "$500", ar: "500 دولار" },
  },
];
export default PriceData;
